version: '3.2'

services:
  app:
    image: nginx:1.13-alpine
    container_name: like_app
    ports:
      - 8003:80/tcp
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./code:/code
      - ./vendor:/vendor
    networks:
      - gallery-internal
      - like-1
    depends_on:
      - php

  php:
    image: uw-php
    container_name: like_php
    volumes:
      - ./vendor:/vendor
      - ./code:/code
    ports:
      - 9000
    depends_on:
      - redis
    networks:
      - gallery-internal
      - like-1

  redis:
    image: redis:4.0.2
    container_name: like_redis
    # command: redis-server --appendonly yes
    # volumes:
    #   - ./data:/data
    networks:
      - like-1

networks:
    gallery-internal:
      external: true
    like-1:
