version: '3.2'

services:
  app:
    image: nginx:1.13-alpine
    container_name: images_app
    ports:
      - 8002:80/tcp
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./code:/code
      - ./vendor:/vendor
    networks:
      - gallery-internal
      - images-1
    depends_on:
      - php

  php:
    image: uw-php
    container_name: images_php
    volumes:
      - ./vendor:/vendor
      - ./code:/code
    ports:
      - 9000
    depends_on:
      - redis
    networks:
      - gallery-internal
      - images-1

  redis:
    image: redis:4.0.2
    container_name: images_redis
    networks:
      - images-1

  python:
    image: app-python:latest
    container_name: images_python
    depends_on: 
      - rabbitmq
      - redis
    networks:
      - images-1
      - gallery-internal

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: images_rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - gallery-internal
      - images-1

networks:
    gallery-internal:
      external: true
    images-1: